from __future__ import annotations

import os
import tempfile

_tmp = tempfile.mkdtemp(prefix="marketedge-test-")
os.environ.update({
    "ENVIRONMENT": "test",
    "DATABASE_URL": f"sqlite:///{_tmp}/test.db",
    "CELERY_ALWAYS_EAGER": "true",
    "SAMPLE_UNIVERSE_SIZE": "24",
    "MARKET_DATA_PROVIDER": "sample",
    "RATE_LIMIT_PER_MINUTE": "100000",
    "AUTH_RATE_LIMIT_PER_MINUTE": "100000",
    "SECRET_KEY": "test-secret-key-that-is-long-enough-123456",
})

import pytest  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

from app.core.db import Base, SessionLocal, engine  # noqa: E402
from app.core.rbac import seed_rbac  # noqa: E402
import app.models  # noqa: E402,F401  (registers tables on Base.metadata)

ADMIN = ("admin@example.com", "Adm1n!Password")


@pytest.fixture(scope="session")
def app_client():
    Base.metadata.create_all(engine)
    db = SessionLocal()
    seed_rbac(db)
    from app.cli import ensure_admin

    ensure_admin(db, *ADMIN)
    db.close()
    from app.main import app

    with TestClient(app) as c:
        yield c


def login(client, email, password, totp=None):
    body = {"email": email, "password": password}
    if totp:
        body["totp_code"] = totp
    r = client.post("/api/v1/auth/login", json=body)
    assert r.status_code == 200, r.text
    return {"Authorization": f"Bearer {r.json()['access_token']}"}


@pytest.fixture(scope="session")
def admin_headers(app_client):
    return login(app_client, *ADMIN)


@pytest.fixture(scope="session")
def scanned(app_client, admin_headers):
    """Ingest SAMPLE data and run one scan (eager Celery) for the whole session."""
    r = app_client.post("/api/v1/admin/jobs/ingest?full=true", headers=admin_headers)
    assert r.status_code == 202
    r = app_client.post("/api/v1/admin/jobs/scan", headers=admin_headers)
    assert r.status_code == 202
    job = app_client.get(f"/api/v1/admin/jobs/{r.json()['job_id']}", headers=admin_headers).json()
    assert job["status"] == "done", job
    return job


def make_user(client, email, role=None, admin_headers=None, password="Str0ng!Passw0rd"):
    r = client.post("/api/v1/auth/register", json={"email": email, "password": password})
    assert r.status_code == 201, r.text
    if role:
        uid = r.json()["id"]
        assert client.patch(f"/api/v1/admin/users/{uid}", json={"role": role}, headers=admin_headers).status_code == 200
    return login(client, email, password)


def any_signal_id(client, headers, api="/api/v1"):
    """A persisted signal from the session scan. The synthetic data is generated by date, so on some days the scan
    has only VALID (or only NO_TRADE) candidates — tests that just need *a* signal must not assume one status."""
    for status in ("NO_TRADE", "VALID"):
        items = client.get(f"{api}/signals?status={status}", headers=headers).json().get("items") or []
        if items:
            return items[0]["id"]
    # synthetic data produced no setup today: persist one clearly-synthetic NO_TRADE signal on the latest scan
    from datetime import date

    from app.core.db import SessionLocal
    from app.models import Instrument, Signal
    from app.services.scan_service import latest_run

    db = SessionLocal()
    try:
        run, ins = latest_run(db, "NSE"), db.query(Instrument).filter(Instrument.symbol == "DEMO_001").one()
        payload = {"symbol": ins.symbol, "market": "NSE", "direction": "LONG", "status": "NO_TRADE", "strategy_id": "breakout_volume",
                   "strategy_name": "Breakout + Volume Confirmation", "strategy": {"id": "breakout_volume", "name": "Breakout + Volume Confirmation"}, "as_of": str(date.today()), "current_price": 100.0,
                   "entry_zone": [100.0, 101.0], "stop": 95.0, "targets": [107.5, 115.0, 122.5], "score": 50.0, "rr_t2": 3.0,
                   "probability": {}, "checks": [], "data": {"is_sample": True}}
        sg = Signal(scan_run_id=run.id, instrument_id=ins.id, symbol=ins.symbol, market="NSE", strategy_key="breakout_volume", direction="LONG",
                    status="NO_TRADE", as_of=date.today(), score=50.0, rr_t2=3.0, sample_size=0, is_sample_data=True, payload=payload)
        db.add(sg)
        db.commit()
        return sg.id
    finally:
        db.close()
