"""news calendars analyst

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 09:12:32.724117
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('impact', sa.String(length=8), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('forecast', sa.Float(), nullable=True),
    sa.Column('previous', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id')
    )
    op.create_index(op.f('ix_economic_events_country'), 'economic_events', ['country'], unique=False)
    op.create_index(op.f('ix_economic_events_event_time'), 'economic_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_economic_events_impact'), 'economic_events', ['impact'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('markets', sa.JSON(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=16), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_method', sa.String(length=32), nullable=False),
    sa.Column('sentiment_terms', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id')
    )
    op.create_index(op.f('ix_news_category'), 'news', ['category'], unique=False)
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_sentiment_label'), 'news', ['sentiment_label'], unique=False)
    op.create_table('news_symbols',
    sa.Column('article_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'symbol')
    )
    op.create_index(op.f('ix_news_symbols_symbol'), 'news_symbols', ['symbol'], unique=False)
    op.create_table('analyst_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('unverified_numbers', sa.JSON(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_queries_created_at'), 'analyst_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyst_queries_user_id'), 'analyst_queries', ['user_id'], unique=False)
    op.create_table('earnings_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=True),
    sa.Column('time', sa.String(length=8), nullable=True),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('eps_actual', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_actual', sa.Float(), nullable=True),
    sa.Column('guidance', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'event_date')
    )
    op.create_index(op.f('ix_earnings_events_event_date'), 'earnings_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_earnings_events_instrument_id'), 'earnings_events', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_events_instrument_id'), table_name='earnings_events')
    op.drop_index(op.f('ix_earnings_events_event_date'), table_name='earnings_events')
    op.drop_table('earnings_events')
    op.drop_index(op.f('ix_analyst_queries_user_id'), table_name='analyst_queries')
    op.drop_index(op.f('ix_analyst_queries_created_at'), table_name='analyst_queries')
    op.drop_table('analyst_queries')
    op.drop_index(op.f('ix_news_symbols_symbol'), table_name='news_symbols')
    op.drop_table('news_symbols')
    op.drop_index(op.f('ix_news_sentiment_label'), table_name='news')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_index(op.f('ix_news_category'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_economic_events_impact'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_event_time'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_country'), table_name='economic_events')
    op.drop_table('economic_events')
    # ### end Alembic commands ###
