"""portfolios alerts notifications

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-30 11:46:44.295527
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('repeat', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_bar', sa.String(length=32), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_kind'), 'alerts', ['kind'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_symbol'), 'alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_link_code', sa.String(length=32), nullable=True),
    sa.Column('telegram_link_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('push_subscriptions', sa.JSON(), nullable=False),
    sa.Column('default_channels', sa.JSON(), nullable=False),
    sa.Column('quiet_start_hour', sa.Integer(), nullable=True),
    sa.Column('quiet_end_hour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_settings_telegram_link_code'), 'notification_settings', ['telegram_link_code'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('starting_capital', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('deliveries', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('portfolio_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('target1', sa.Float(), nullable=True),
    sa.Column('target2', sa.Float(), nullable=True),
    sa.Column('partial_at_t1', sa.Float(), nullable=False),
    sa.Column('commission_pct', sa.Float(), nullable=False),
    sa.Column('slippage_pct', sa.Float(), nullable=False),
    sa.Column('taxes', sa.Float(), nullable=False),
    sa.Column('brokerage', sa.Float(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('exit_reason', sa.String(length=24), nullable=True),
    sa.Column('realized', sa.Float(), nullable=False),
    sa.Column('costs', sa.Float(), nullable=False),
    sa.Column('fx_to_base_entry', sa.Float(), nullable=True),
    sa.Column('fx_to_base_exit', sa.Float(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_hold_bars', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('close_requested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_trades_portfolio_id'), 'portfolio_trades', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_trades_status'), 'portfolio_trades', ['status'], unique=False)
    op.create_index(op.f('ix_portfolio_trades_symbol'), 'portfolio_trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_trades_symbol'), table_name='portfolio_trades')
    op.drop_index(op.f('ix_portfolio_trades_status'), table_name='portfolio_trades')
    op.drop_index(op.f('ix_portfolio_trades_portfolio_id'), table_name='portfolio_trades')
    op.drop_table('portfolio_trades')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_notification_settings_telegram_link_code'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_symbol'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_kind'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
