"""ml models

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-30 10:13:05.216950
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('algo', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('source_scan_run_id', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('is_sample_data', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_scan_run_id'], ['scan_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'target', 'version')
    )
    op.create_index(op.f('ix_ml_models_market'), 'ml_models', ['market'], unique=False)
    op.create_index(op.f('ix_ml_models_status'), 'ml_models', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_models_status'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_market'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
