"""options chain

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 20:27:22.375423
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_id', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['underlying_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying_id', 'expiry', 'strike', 'option_type')
    )
    op.create_index(op.f('ix_options_contracts_expiry'), 'options_contracts', ['expiry'], unique=False)
    op.create_index(op.f('ix_options_contracts_underlying_id'), 'options_contracts', ['underlying_id'], unique=False)
    op.create_table('options_iv_history',
    sa.Column('underlying_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('atm_iv', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['underlying_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('underlying_id', 'as_of')
    )
    op.create_table('options_chain',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('ltp', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('oi', sa.Float(), nullable=False),
    sa.Column('oi_change', sa.Float(), nullable=False),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['options_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', 'snapshot_ts')
    )
    op.create_index('ix_options_chain_snapshot', 'options_chain', ['snapshot_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_options_chain_snapshot', table_name='options_chain')
    op.drop_table('options_chain')
    op.drop_table('options_iv_history')
    op.drop_index(op.f('ix_options_contracts_underlying_id'), table_name='options_contracts')
    op.drop_index(op.f('ix_options_contracts_expiry'), table_name='options_contracts')
    op.drop_table('options_contracts')
    # ### end Alembic commands ###
