"""strategy versions portfolio

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 21:58:09.964348
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version')
    )
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.add_column('backtest_trades', sa.Column('t1_date', sa.Date(), nullable=True))
    op.add_column('backtests', sa.Column('strategy_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_backtests_strategy_version_id', 'backtests', 'strategy_versions', ['strategy_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('strategies', sa.Column('current_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('strategies', sa.Column('include_in_scan', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###
    # Data migration: strategies created before versioning get an immutable v1 from their current definition.
    op.execute("""
        INSERT INTO strategy_versions (strategy_id, version, definition, note, created_by, created_at)
        SELECT s.id, 1, s.definition, 'Migrated from pre-versioning definition', s.owner_id, s.created_at
        FROM strategies s
        WHERE s.is_builtin = false
          AND NOT EXISTS (SELECT 1 FROM strategy_versions v WHERE v.strategy_id = s.id)
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'include_in_scan')
    op.drop_column('strategies', 'current_version')
    op.drop_constraint('fk_backtests_strategy_version_id', 'backtests', type_='foreignkey')
    op.drop_column('backtests', 'strategy_version_id')
    op.drop_column('backtest_trades', 't1_date')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    # ### end Alembic commands ###
