"""multi market

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-30 00:43:30.364517
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_derivatives',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('funding_rate', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('long_short_ratio', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'as_of')
    )
    op.add_column('instruments', sa.Column('market', sa.String(length=16), server_default='NSE', nullable=False))
    op.create_index(op.f('ix_instruments_market'), 'instruments', ['market'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_market'), table_name='instruments')
    op.drop_column('instruments', 'market')
    op.drop_table('crypto_derivatives')
    # ### end Alembic commands ###
